### ISSUE TITLE
Can't install release v0.3.9

### ISSUE THREAD

**Issue by iZhangHui** [sipeed/Maixduino#19]
Arduino IDE 1.8.9 on Windows 10 couldn't display and install v0.3.9 release. So I can't use Maixduino Board.
![maixduino](https://user-images.githubusercontent.com/6889915/60143938-3d220e80-97f3-11e9-9390-e959cc02208d.jpg)

**Comment by iZhangHui** [comment]
@btx000 Could you help to check this issue?  Can't waiting for testing my Maixduino Board.

**Comment by bitsk** [comment]
Sorry, I don't have much time to deal with these issues right now. There are temporary solutions here.
* Replace kflash with the following program
[kflash_py.zip](https://github.com/sipeed/Maixduino/files/3329293/kflash_py.zip)
* Complete the clone from this repository to the core folder.

We will update the 0.3.9 version of the installation link within a few days.

**Comment by ghost** [comment]
Hi, I have the same problem with Ubuntu 18.04.
There is only version 0.3.8 in Arduino IDE board manager on Linux too.
The zip file is for Windows (kflash_py.exe), is there a version for Linux ?
thank you!

**Comment by ghost** [comment]
I have flashed with kflash_gui, it works !
[kflash_gui](https://github.com/sipeed/kflash_gui/archive/master.zip)

**Comment by iZhangHui** [comment]
A week has passed. :(

**Comment by bitsk** [comment]
Now you can install v0.3.9 normally in arduino ide and pio ide. If you have any problems, please give me feedback.

**Comment by lights0123** [comment]
@btx000 On PIO, I get the following error ([the same happens on Windows](https://github.com/sipeed/platform-kendryte210/issues/11)):
```
PackageManager: Installing framework-maixduino @ ~0.3.9
Error: Could not find a version that satisfies the requirement '~0.3.9' for your system 'linux_x86_64'
```

**Comment by lights0123** [comment]
The above was fixed with [this issue](https://github.com/sipeed/platform-kendryte210/issues/12).
