### ISSUE TITLE
mobilenet_v1.ino can't load model file on Maixduino board

### ISSUE THREAD

**Issue by iZhangHui** [sipeed/Maixduino#29]
SPIClass spi0(SPI0);  // MUST be SPI0 for Maix series on board LCD
Sipeed_ST7789 lcd(320, 240, spi0);

https://github.com/sipeed/Maixduino/blob/b47d512182bfb518270f60dc3a6e15e72b5dadb5/libraries/Maix_KPU/examples/mobilenet_v1/MBNet_1000.cpp#L40
SD card use SPI1 for default. Actually, it should also use SPI0 on Maixduino board. #26 

Is there any conflicts? How to fix this issue?

**Comment by bitsk** [comment]
Their cs pins are different so they don't cause conflicts.
This problem is an SD card initialization bug that has been fixed in #26 and you can burn the sample program directly.

**Comment by iZhangHui** [comment]
Great. It works. Thank you.
