### ISSUE TITLE
can't find LED_BUILTIN on the Maixduno board

### ISSUE THREAD

**Issue by iZhangHui** [sipeed/Maixduino#30]
https://github.com/sipeed/Maixduino/blob/240bb27d0b53c2ddb246a8bdf2a10692bdc001dc/variants/sipeed_maixduino/pins_arduino.h#L23

![批注 2019-07-17 110526](https://user-images.githubusercontent.com/6889915/61344159-d8525500-a882-11e9-88f2-35414bb2b792.jpg)

**Comment by bitsk** [comment]
Maixduino board does not have build-in led, this macro definition is reserved for compatibility with the blink example.

**Comment by iZhangHui** [comment]
I suggest that adding one for next hardware revision, or it will lead to confusion. :)
Thank you for your explanation.
