### ISSUE TITLE
Maixduino Development Desktop Platform

### ISSUE THREAD

**Issue by baqwas** [sipeed/Maixduino#36]
Is it possible to do Maixduino development work on the following desktop client platform:
```
Linux BeUlta 5.0.0-21-generic #22-Ubuntu SMP Tue Jul 2 13:27:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
```
I have the board identified as Sipeed Maixduino and the Port and Programmer settings as advised in the Maixduino documentation. The on-board LED does not blink. The output window displays:
```
Programming BIN: |=============================================================================================================================================================================================================================================================================================================================================================================================================================================================| 100.0% 53kiB/s
[INFO] Rebooting... 
```
Can I use Ubuntu 19.04 connected to Maixduino via USB port for development tests? Is there any reference documentation?

Thanks for any feedback. Kind regards.

**Comment by bitsk** [comment]
You can control the on-board TX led by controlling pin 1 or by connecting LEDs on other pins. The board does not have a led for blink.
