### ISSUE TITLE
COM Name

### ISSUE THREAD

**Issue by mushroom-x** [sipeed/Maixduino#4]
Install maxiduino, the serial port  name will always be Sipeed "Maix One Dock...", even if connect Arduino Uno Board
![Screenshot from 2019-04-23 13-41-06](https://user-images.githubusercontent.com/13478703/56557554-203c4580-65ce-11e9-9559-04011ece042c.png)

**Comment by bitsk** [comment]
@mushroom-x 
Thanks for your feedback, this issue has been fixed in v0.3.7. You may try to update.
