### ISSUE TITLE
K210 not detected

### ISSUE THREAD

**Issue by baqwas** [sipeed/Maixduino#48]
Hello!
I have used two different cables and two different ports to connect to Maixduino from Ubuntu 19.04 desktop. I have had ZERO luck. Attached is a summary of my exercise. I can provide additional details upon request.

Will someone at Sipeed be kind enough to help me with this persistent and repeatable issue?

Xie xie.
[MicroPython local build firmware.docx](https://github.com/sipeed/Maixduino/files/3570837/MicroPython.local.build.firmware.docx)

**Comment by vanvuongngo** [comment]
Hi baqwas,

I am using ubuntu 19.04 as well. Did you executed following to have access to the serial port?
```
sudo usermod -a -G dialout $(whoami)
```
see install documentation under https://maixduino.sipeed.com/en/get_started/install.html
I use platform.io instead of Arduino IDE but the preparation instruction is the same.

**Comment by baqwas** [comment]
Hello Van,

Thank you for your suggestion. Of course, I did set the permission (along the lines _you have suggested_) a very long time ago! I have five other Arduino boards (different types) working without any issue. I can upload to these boards from the Arduino default IDE without any issue (except for the occasional reset for operational reasons). Yes, I am diligently ensuring that the right settings combinations board/port/flash are set before attempting to upload to a specific board.

I understand the productivity advantages of **platform.io** especially when it is used in conjunction with, for example, Visual Studio Code but my needs are very modest. Right now I want to keep things simple and just focus on reading/writing to one or two pins let alone work on RISC-V magic that may happen later.

FWIW, @loboris provided an alternate development, **MicroPython**, approach that I found very interesting.

Kind regards.

**Comment by vanvuongngo** [comment]
Hi Matha,

I can reproduce your problem and it could be that the automatic recognition of the board does not work for you either. You can try to set a board manually with the argument ```-B```. Possible options are kd233, dan, bit, goD, goE or trainer. I have a MaixGo and it works when I execute following (port automaticlly detected on ```/dev/ttyUSB1```):
```
./kflash.py -BgoE -b 2000000 -t MaixPy.bin
```
Hope it will helps you and I can understand if you want to use ```python```. It's not my favorite programming language but it also has its advantages.

**Comment by vanvuongngo** [comment]
Or use ```MicroPython``` from sipeed instead, see https://maixpy.sipeed.com/en/get_started/upgrade_firmware.html

1. get a firmware (file with ```.bin``` extension) from https://github.com/sipeed/MaixPy/releases
2. get ```kflash_gui``` flasher from https://github.com/sipeed/kflash_gui
3. install ```MaixPy IDE``` link can be found under http://dl.sipeed.com/MAIX/MaixPy/ide/ or use a serial port command line tool like ```screen```

**Comment by vanvuongngo** [comment]
@baqwas, your problem would be better placed in the MaixPy area see https://github.com/sipeed/MaixPy

**Comment by baqwas** [comment]
Hello Van,

You are correct wtih your observation about the -**BgoE** option. That was the only way I could get the MicroPython to flash.

I'll try your suggestion on the MaixPy IDE. Right that is probably the more productive option for me. Again, really appreciate your assistance and guidance. Without your feedback (and that from @loboris), I would be floundering.

Kind regards.

P.S. The Serial-USB-C chip has apparent speed limitations well below the published spec;  I have to use a lower speed ~1.1Mbps. Perhaps, this is the root cause of my issue? I am plugging directly from the (ASUS H370-PRIME) motherboard to the board (and I have tried three different cables) - no external hub.

**Comment by vanvuongngo** [comment]
> P.S. The Serial-USB-C chip has apparent speed limitations well below the published spec; I have to use a lower speed ~1.1Mbps. Perhaps, this is the root cause of my issue? I am plugging directly from the (ASUS H370-PRIME) motherboard to the board (and I have tried three different cables) - no external hub.

Nice and I guess the ```kflash.py``` script has a bug but I did not debug it. Feel free to close this issue when you can work now.

**Comment by baqwas** [comment]
Thx to the guidance and feedback from @vanvuongngo  and @loboris, I have sufficient workaround suggestions to evaluate. Closing the issue accordingly.

**Comment by matheus-giordani** [comment]
I have the same problem but in Windows 10. I already installed the drivers following the step by step instructions in the documentation [tutorial](https://wiki.sipeed.com/soft/maixpy/en/get_started/install_driver/duino.html), but so far nothing, could anyone help me?
## board: k210
## event error:
Log Name:      Microsoft-Windows-Kernel-PnP/Configuration
Source:        Microsoft-Windows-Kernel-PnP
Date:          2/21/2024 7:30:56 PM
Event ID:      411
Task Category: None
Level:         Error
Keywords:      
User:          SISTEMA
Computer:      DESKTOP-C0S1FCA
Description:
Device USB\VID_0000&PID_0002\5&1f57c5c5&0&3 had a problem starting.

Driver Name: usb.inf
Class Guid: {36fc9e60-c465-11cf-8056-444553540000}
Service: 
Lower Filters: 
Upper Filters: 
Problem: 0x2B
Problem Status: 0x0
Event Xml:
```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Kernel-PnP" Guid="{9c205a39-1250-487d-abd7-e831c6290539}" />
    <EventID>411</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x4000000000000000</Keywords>
    <TimeCreated SystemTime="2024-02-21T22:30:56.4158472Z" />
    <EventRecordID>544</EventRecordID>
    <Correlation />
    <Execution ProcessID="4" ThreadID="2656" />
    <Channel>Microsoft-Windows-Kernel-PnP/Configuration</Channel>
    <Computer>DESKTOP-C0S1FCA</Computer>
    <Security UserID="S-1-5-18" />
  </System>
  <EventData>
    <Data Name="DeviceInstanceId">USB\VID_0000&amp;PID_0002\5&amp;1f57c5c5&amp;0&amp;3</Data>
    <Data Name="DriverName">usb.inf</Data>
    <Data Name="ClassGuid">{36fc9e60-c465-11cf-8056-444553540000}</Data>
    <Data Name="ServiceName">
    </Data>
    <Data Name="LowerFilters">
    </Data>
    <Data Name="UpperFilters">
    </Data>
    <Data Name="Problem">0x2b</Data>
    <Data Name="Status">0x0</Data>
  </EventData>
</Event>
```
![error_1](https://github.com/sipeed/Maixduino/assets/74312355/6aa2132e-b68a-405c-a69d-ab7556b12fdb)
