### ISSUE TITLE
Cannot download support library

### ISSUE THREAD

**Issue by baqwas** [sipeed/Maixduino#49]
Hello!
I cannot download the libraries for the Maixduino board under Arduino IDE. Two screen shots are attached for reference purposes.

Can anyone help me to resolve the issue, please?

Thanks.
![Error downloading status](https://user-images.githubusercontent.com/7071255/64199203-655f6680-ce4f-11e9-9329-e930ed4fab2e.png)
![Error downloading output window](https://user-images.githubusercontent.com/7071255/64199206-67292a00-ce4f-11e9-9bc3-3ac4af427081.png)
![Boards Manager Maixduino Install](https://user-images.githubusercontent.com/7071255/64199213-6a241a80-ce4f-11e9-89b4-c776bacc8279.png)

**Comment by chegewara** [comment]
There is 2 json files to download maixduino, please try the other one:
http://dl.sipeed.com/MAIX/Maixduino/package_Maixduino_k210_index.json

**Comment by baqwas** [comment]
Hello @chegewara 

I've attached the screen shots of the Board Manager settings in use. I do believe that the settings are the default ones for the **Maixduino** board with **USB0** and **k-flash**. Appreciate the quick response but I'm still stuck.

Kind regards.
![Other library](https://user-images.githubusercontent.com/7071255/64208273-196aec80-ce64-11e9-86f5-ea666c3530fb.png)
![Boards Manager Maixduino Install](https://user-images.githubusercontent.com/7071255/64208158-d741ab00-ce63-11e9-9f44-3addedae4430.png)
![Boards manager settings](https://user-images.githubusercontent.com/7071255/64208159-d741ab00-ce63-11e9-85a6-4186127f4bc3.png)

**Comment by chegewara** [comment]
From screenshots it looks like you have all installed and yes, k-flash is the correct one programmer.
The most recent version is 0.3.10 and i dont have problems to flash maixduino on my ubuntu 14.10 and arduino-ide.

Just in case you can try to turn on flashing mode with onboard buttons (press both btns and 1st release pwr).

**Comment by baqwas** [comment]
@chegewara 

> turn on flashing mode with onboard buttons (press both btns and 1st release pwr)

That is precisely what I have done _repeatedly_ prior to seeking help by logging an issue! That is my routine operational mode with Arduino when there there are unpredictable freezes in the output pane.

The reason I'm pursuing this issue after a lapse of attention is that the Maixduino and the Grove AI HAT both have similar issues (my simplistic assumption) - **not detecting K210**. It is quite conceivable that the two anomalies are distinctly separate but the inability to run the simplest standard exercise using all the documented steps (except that I'm on Ubuntu 19.04) for both boards is perplexing owing to my limited knowledge in these matters.

Kind regards.

**Comment by chegewara** [comment]
Yes, it can be the reason on Ubuntu 19.04.
@Neutree help

**Comment by baqwas** [comment]
In that case, let me wait for Ubuntu 19.10 next month and assess whether that would help out.

Thanks everyone.

**Comment by yulonglovecode** [comment]
hi i still face this problem , anyone know why i cant download the library with the URL given for the preference given?
