### ISSUE TITLE
can't open the file from SD card

### ISSUE THREAD

**Issue by WangFengtu1996** [sipeed/Maixduino#7]
在我烧录人脸识别Demo时，无法读取SD卡内的模型文件。

**Comment by bitsk** [comment]
用的是例程？我测试要把文件名改成一个字母才可以读取

**Comment by WangFengtu1996** [comment]
是，我将模型文件名改为了m，开始还是不能读取，放回错误码-4




------------------ 原始邮件 ------------------
发件人: "Bits"<notifications@github.com>;
发送时间: 2019年5月13日(星期一) 下午4:25
收件人: "sipeed/Maixduino"<Maixduino@noreply.github.com>;
抄送: "渣渣图"<1148791151@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [sipeed/Maixduino] can't open the file from SD card (#7)




用的是例程？我测试要把文件名改成一个字母才可以读取

**Comment by bitsk** [comment]
方便把模型发给我测试吗？排除一下tf卡质量问题

**Comment by WangFengtu1996** [comment]
模型就是官方提供的模型，我直接解压，改名。



------------------ 原始邮件 ------------------
发件人: "Bits"<notifications@github.com>; 
发送时间: 2019年5月13日(星期一) 下午5:23
收件人: "sipeed/Maixduino"<Maixduino@noreply.github.com>; 
抄送: "渣渣图"<1148791151@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [sipeed/Maixduino] can't open the file from SD card (#7)




方便把模型发给我测试吗？排除一下tf卡质量问题

**Comment by Neutree** [comment]
请先测试SD卡示例保证卡使用没问题

**Comment by WangFengtu1996** [comment]
好的，谢谢。对于SD卡有推荐使用的么




------------------ 原始邮件 ------------------
发件人: "Neucrack"<notifications@github.com>; 
发送时间: 2019年5月13日(星期一) 下午5:33
收件人: "sipeed/Maixduino"<Maixduino@noreply.github.com>; 
抄送: "渣渣图"<1148791151@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [sipeed/Maixduino] can't open the file from SD card (#7)




请先测试SD卡示例保证卡使用没问题
