### ISSUE TITLE
how is this model generated?

### ISSUE THREAD

**Issue by laurentopia** [sipeed/Maixduino#8]
https://github.com/sipeed/Maixduino/blob/master/libraries/Maix_Speech_Recognition/examples/voice_control_led_en/voice_model.h

**Comment by bitsk** [comment]
Hi, @laurentopia 
We provide a simple routine for outputting the sound model. You only need to upload the program to the maix go board, speak to the board, and then the voice model will be printed on the serial port.
https://github.com/sipeed/Maixduino/blob/master/libraries/Maix_Speech_Recognition/examples/get_voice_model/get_voice_model.ino

Alternatively, you can use `rec.record(keyword_num, model_num)` in the program to save the model directly into memory, thus real-time adding models and recognition.

It should be noted that you can only set up to 4 voice models for a keyword, up to 20 keywords.

**Comment by laurentopia** [comment]
Thank you @btx000.
